### ISSUE TITLE
Script error spamming error log

### ISSUE THREAD

**Issue by Leviathonlx** [TypicalCrusader/T4N-Tributaries-Framework#19]
This error is created multiple times a second.

[00:15:03][jomini_script_system.cpp:208]: Script system error!
  Error: Invalid left side during comparison 'compare_value'
  Script location: file: common/casus_belli_types/00_T4N_tributary_war.txt line: 131

**Comment by TypicalCrusader** [comment]
`scope:attacker.tier >= scope:defender.primary_title.tier` 
will fix this today along with cultural groups remnant in chracter interactions

**Comment by TypicalCrusader** [comment]
Fixed
