### ISSUE TITLE
Tributaries are immune to hostile action

### ISSUE THREAD

**Issue by Leviathonlx** [TypicalCrusader/T4N-Tributaries-Framework#20]
The way the casus belli block is made makes it so a tributary is basically immune to outside forces since you can't declare war on the tributary nor can you declare war on the suzerain for the tributary. 

The casus_belli_block does give an error about missing perspective but not sure if this is the issue or if that's just causing an issue with the tooltip.

**Comment by TypicalCrusader** [comment]
Fixed both, i forgor💀to add my_suzerain check and did wrong comparison
