### ISSUE TITLE
Tributaries no longer pass to heirs

### ISSUE THREAD

**Issue by Leviathonlx** [TypicalCrusader/T4N-Tributaries-Framework#25]
Not sure if this has been abandoned at this point but if not then it seems that the 1.9 changes made it so tributaries no longer pass to heirs/variables aren't properly setting.

[21:56:21][jomini_script_system.cpp:276]: Script system error!
  Error: Failed to fetch variable for 'my_suzerain' due to not being set
  Script location: file: common/scripted_effects; define_tributary line: 30
 file: common/on_action/T4N_tributaries_on_action.txt line: 207
 file: common/scripted_effects; pass_tributary_type_to_heir line: 20
 file: common/scripted_effects; make_tributary line: 2
 file: common/scripted_effects; tributary_permanent line: 2

[21:56:21][jomini_script_system.cpp:276]: Script system error!
  Error: Event target link 'var' returned an unset scope
  Script location: file: common/scripted_effects; define_tributary line: 30
 file: common/on_action/T4N_tributaries_on_action.txt line: 207
 file: common/scripted_effects; pass_tributary_type_to_heir line: 20
 file: common/scripted_effects; make_tributary line: 2
 file: common/scripted_effects; tributary_permanent line: 2

[21:56:43][jomini_script_system.cpp:276]: Script system error!
  Error: Failed to fetch variable for 'my_suzerain' due to not being set
  Script location: common/scripted_triggers
 file: common/character_interactions/T4N_tributaries_interactions.txt line: 570

[21:56:43][jomini_script_system.cpp:276]: Script system error!
  Error: Event target link 'var' returned an unset scope
  Script location: common/scripted_triggers
 file: common/character_interactions/T4N_tributaries_interactions.txt line: 570

[21:56:43][jomini_script_system.cpp:276]: Script system error!
  Error: var:my_suzerain trigger [ Failed context switch ]
  Script location: file: common/scripted_triggers; is_tributary line: 3
 file: common/character_interactions/T4N_tributaries_interactions.txt line: 570

[21:56:43][jomini_script_system.cpp:276]: Script system error!
  Error: Failed to fetch variable for 'my_suzerain' due to not being set
  Script location: common/scripted_triggers
 file: common/character_interactions/T4N_tributaries_interactions.txt line: 570

[21:56:43][jomini_script_system.cpp:276]: Script system error!
  Error: Event target link 'var' returned an unset scope
  Script location: common/scripted_triggers
 file: common/character_interactions/T4N_tributaries_interactions.txt line: 570

[21:56:43][jomini_script_system.cpp:276]: Script system error!
  Error: var:my_suzerain trigger [ Failed context switch ]
  Script location: file: common/scripted_triggers; is_tributary line: 3
 file: common/character_interactions/T4N_tributaries_interactions.txt line: 570

**Comment by TypicalCrusader** [comment]
not abandoned but simply does not have time to fix it

**Comment by TypicalCrusader** [comment]
will try to fix and make it work with 1.9 when i will have time

**Comment by TypicalCrusader** [comment]
fixed
