### ISSUE TITLE
Stray NAND

### ISSUE THREAD

**Issue by amtep** [TypicalCrusader/T4N-Tributaries-Framework#26]
https://github.com/TypicalCrusader/T4N-Tributaries-Framework/blob/85334721679470bb8600f3777364a1b7f686736f/TTS/common/casus_belli_types/00_T4N_tributary_war.txt#L13

I'm pretty sure that NAND should be a NOR.

NAND means "these are not all true at the same time"
NOR means "none of these are true"

**Comment by TypicalCrusader** [comment]
not a bug, it was intended
